language: cpp
compiler: gcc
before_install:
install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq g++ gcc libtiff4 qt4-dev-tools qt4-qmake libusb-1.0-0
    - wget ftp://ftp.sbig.com/pub/devsw/LinuxDevKit.tar.gz
    - tar -xzf LinuxDevKit.tar.gz
    - sudo cp LinuxDevKit/x86/c/lib64/libsbigudrv.so /usr/local/lib
    - sudo cp LinuxDevKit/x86/c/testapp/sbigudrv.h /usr/local/include
    - ./configure && make
script:
    - echo "Bravo"
notifications:
    email: false
